version: "3"
services: 
    db:
        container_name: db
        image: mysql:5
        ports: 
            - "3306:3306"
        volumes: 
            - ./db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: react
            MYSQL_USER: react
            MYSQL_PASSWORD: react
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    front:
        container_name: front
        image: node
        tty: true
        links:
            - api
        ports: 
            - "3000:3000"
        volumes: 
            - ./front:/app
        working_dir: "/app"
        environment: 
            NODE_ENV: development
            TZ: Asia/Tokyo
        # command: bash -c "cd react-app && npm start"

    api:
        container_name: api
        image: node
        tty: true
        links: 
            - db
        ports: 
            - "8080:8080"
        volumes: 
            - ./api:/app
        working_dir: "/app"
        environment: 
            NODE_ENV: development
            PORT: 8080
            TZ: Asia/Tokyo
            DB_HOSTNAME: db
            DB_NAME: react
            DB_USERNAME: react
            DB_PASSWORD: react
        # command: bash -c "cd react-api && npm run dev"